# Generated by Django 3.2.2 on 2021-05-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simple',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='simple',
            name='url',
            field=models.URLField(default='some default', max_length=100),
        ),
    ]
