# Generated by Django 3.2.2 on 2021-05-11 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0005_framework_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framework',
            name='lanugage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='example.language'),
        ),
    ]
